=== Tomkolda/ZSG/faktura.dtd
<!ELEMENT faktura (odberatel,dodavatel,polozka+)> <!-- plus znamená alespoň jednou -->
<!ELEMENT odberatel (nazev,adresa,ico)>
<!ELEMENT dodavatel (nazev,adresa,ico)>
<!ELEMENT polozka (popis?,cena,dph)> <!-- otazník znamená maximálně jednou -->
<!ELEMENT nazev (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>
<!ELEMENT ico (#PCDATA)>
<!ELEMENT popis (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT dph (#PCDATA)>
<!ATTLIST faktura
          cislo CDATA #REQUIRED
          vystaveni CDATA #REQUIRED
          splatnost CDATA #REQUIRED
          vystavil CDATA #IMPLIED> <!-- #REQUIRED znamená, že atribut musí být uveden; #IMPLIED, že je nepovinný -->
<!ATTLIST cena
          mena CDATA "Kč"> <!-- výchozí (default) hodnota -->
<!ATTLIST polozka
          ks CDATA "1">

=== Tomkolda/ZSG/faktura-pripojene_DTD.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE faktura SYSTEM "faktura.dtd">
<faktura cislo="7/2016" vystaveni="27.3.2016" splatnost="10.4.2016">
	<odberatel>
		<nazev>BZSG, s.r.o.</nazev>
		<adresa>Kolejní 2, Brno, 61200</adresa>
		<ico>0123456789</ico>
	</odberatel>
	<dodavatel>
		<nazev>XSL+XML s.r.o.</nazev>
		<adresa>Voříškova 13, Brno, 61320</adresa>
		<ico>123654789</ico>
	</dodavatel>
	<polozka>
		<popis>Nasazení šablon XSL do XML</popis>
		<cena>159000</cena>
		<dph>21</dph>
	</polozka>
	<polozka>
		<popis>XSL procesor</popis>
		<cena mena="EUR">99</cena>
		<dph>21</dph>
	</polozka>
	<polozka ks="3">
		<popis>Stolní počítač</popis>
		<cena>20990</cena>
		<dph>21</dph>
	</polozka>
</faktura>
